client:
  devopsNavs:
    - cate: ''
      items:
      - name: pipelines
        title: PIPELINE_PL
        icon: application
      - name: cd
        title: CONTINUOUS_DEPLOYMENT_PL
        icon: rocket
        authKey: applications
        requiredClusterVersion: v3.3.0
      - name: code-repo
        title: CODE_REPO_PL
        icon: code
        authKey: gitrepositories
        requiredClusterVersion: v3.3.0
      - name: management
        title: DEVOPS_PROJECT_SETTINGS
        icon: cogwheel
        open: true
        children:
        - name: base-info
          title: BASIC_INFORMATION
          skipAuth: true
        - name: credentials
          title: CREDENTIAL_PL
        - name: roles
          title: DEVOPS_PROJECT_ROLE_PL
        - name: members
          title: DEVOPS_PROJECT_MEMBER_PL